name: release

on:
  release:
    types:
      - published

env:
  DH_IMAGE: docker.io/marvinmenzerath/putr
  GHCR_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: login github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.DH_IMAGE }}:${{ github.event.release.tag_name }},${{ env.GHCR_IMAGE }}:${{ github.event.release.tag_name }},${{ env.DH_IMAGE }}:latest,${{ env.GHCR_IMAGE }}:latest
          push: true
